### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by fakeowl1** [vosmiic/jellyfin-ani-sync#164]
In my jellyfin sync to anilist not working.

**Logs**

[jellyfin.log](https://github.com/user-attachments/files/17683816/jellyfin.log)

**Expected behavior**

**Screenshots**

![2024-11-08_22:25:25](https://github.com/user-attachments/assets/51248c63-0185-40ef-81e3-52de4908eb74)

![2024-11-08_22:26:11](https://github.com/user-attachments/assets/4876534c-1a8b-451c-bb58-a8d87e5a9f2d)

![2024-11-08_22:26:53](https://github.com/user-attachments/assets/045157fe-87ce-41f4-b90d-4e59c750d5b2)

![2024-11-08_22:28:02](https://github.com/user-attachments/assets/88ff0696-0a45-4dad-80c2-a61ad1170c33)

![image](https://github.com/user-attachments/assets/5af8df0d-e8d0-4ec7-a8de-53e512ab3575)

**Comment by sean-mcgauley** [comment]
I was having the same issue earlier today with Anisync to MAL.

Restarting my Jellyfin server fixed the issue so I would try that for now as a temporary fix.

**Comment by vosmiic** [comment]
If the issue is related to manually syncing, a bug was found due to a change in the latest version of Jellyfin and it has been fixed in [the latest beta release](https://github.com/vosmiic/jellyfin-ani-sync/releases/tag/v3.6b). This bug fix will be included in the next stable release which will be released in a few weeks.

If it is not related to manual syncing, I cannot see any issues in the logs related to the plugin. Please try watching another piece of media and share the latest Jellyfin log file (with all sensitive data removed). The entire log file does not need to be shared, just the appropriate error if you are able to identify it will do.

**Comment by Kunal926** [comment]
This was probably due to AniList API has being temporarily disabled.I found this in my jellyfin server logs

[2024-11-10 21:25:44.846 +05:30] [ERR] [32] jellyfin_ani_sync.Api.AuthApiCall: Unable to complete AniList API call (POST https://graphql.anilist.co), reason: Forbidden, content: 
{
    "errors": [
        {
            "message": "The AniList API has been temporarily disabled due to severe stability issues. Please check the official AniList Discord for more information.",
            "status": 403,
            "locations": [
                {
                    "line": 1,
                    "column": 1
                }
            ]
        }
    ],
    "data": null
}

**Comment by sean-mcgauley** [comment]
This is related to automatic updating in my case and it looks like the issue came back.

in the attached logs you can see Anisync working correctly for Dandadan yesterday and it’s updating in MAL but after watching a couple of episodes of Makeine more recently it appears to stop working.  Whatever’s causing it to not update appears to be related to this line:

“ jellyfin_ani_sync.UpdateProviderStatus: (Anidb) Anime already has AniDb ID; no need to look it up ”

[Anisync Log.txt](https://github.com/user-attachments/files/17723882/Anisync.Log.txt)

**Comment by vosmiic** [comment]
Hard to see why a restart would change anything if you are testing it on the same episode. Could you refresh the metadata of the series and see if you still run into the issue?

**Comment by sean-mcgauley** [comment]
I attempted replacing all metadata and still ran into the same issue. The plugin only functions correctly again once the Jellyfin server has been fully restarted and the episode is checked as "watched" again.

When the plugin fails to update MAL the only log messages that are present are:

[2024-12-08 01:11:32.544 +00:00] [INF] [56] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Android TV" "0.17.9" playing "The Subs Take to the Stage". Stopped at "0" ms
[2024-12-08 01:11:33.951 +00:00] [INF] [56] jellyfin_ani_sync.UpdateProviderStatus: (Anidb) Anime already has AniDb ID; no need to look it up

and when it is successful after a server restart and unchecking/rechecking the episode:
[2024-12-08 02:21:45.254 +00:00] [INF] [17] jellyfin_ani_sync.UpdateProviderStatus: (Tvdb) Anime reference found in anime list XML
[2024-12-08 02:21:45.263 +00:00] [WRN] [17] jellyfin_ani_sync.UpdateProviderStatus: (AniDb) Could not lookup using absolute episode number (reason: no mappings found)
[2024-12-08 02:21:45.266 +00:00] [INF] [17] jellyfin_ani_sync.UpdateProviderStatus: Looking up AniDB by season offset
[2024-12-08 02:21:45.268 +00:00] [INF] [17] jellyfin_ani_sync.UpdateProviderStatus: (Tvdb) Anime Blue Lock found in anime XML file, detected AniDB ID 17954
[2024-12-08 02:21:45.268 +00:00] [INF] [17] jellyfin_ani_sync.UpdateProviderStatus: Retrieving provider IDs from offline database for AniDb ID 17954...
[2024-12-08 02:21:45.698 +00:00] [INF] [17] jellyfin_ani_sync.UpdateProviderStatus: Retrieved provider IDs
[2024-12-08 02:21:45.698 +00:00] [INF] [17] jellyfin_ani_sync.UpdateProviderStatus: Using provider Mal...
[2024-12-08 02:21:45.698 +00:00] [INF] [17] jellyfin_ani_sync.Api.MalApiCalls: Retrieving an anime from MAL (GET https://api.myanimelist.net/v2/anime/54865?fields=title%2Crelated_anime%2Cmy_list_status%2Cnum_episodes)...
[2024-12-08 02:21:45.848 +00:00] [INF] [17] jellyfin_ani_sync.Api.MalApiCalls: Anime retrieval complete
[2024-12-08 02:21:45.848 +00:00] [INF] [17] jellyfin_ani_sync.UpdateProviderStatus: (Mal) Series (Blue Lock vs. U-20 Japan) found on watching list
[2024-12-08 02:21:46.206 +00:00] [INF] [17] jellyfin_ani_sync.Api.MalApiCalls: Updating anime status (PUT https://api.myanimelist.net/v2/anime/54865/my_list_status)...
[2024-12-08 02:21:46.210 +00:00] [INF] [17] jellyfin_ani_sync.Api.MalApiCalls: Update complete
[2024-12-08 02:21:46.210 +00:00] [INF] [17] jellyfin_ani_sync.UpdateProviderStatus: (Mal) Updated series (Blue Lock vs. U-20 Japan) progress to 10

**Comment by vosmiic** [comment]
Could you share your metadata entries for the season and series you are testing this on? Specifically those under "External IDs".

**Comment by sean-mcgauley** [comment]
Makeine series:
AniDB Id - 18317
IMDb Id - tt32332831
TheMovieDb Series Id - 241535
TheTVDB Numerical Series Id - 443377

Makeine Season 1:
TVDB Season ID - 2098885

Makeine S1E4 (When You Stare Into a Losing Heroine, the Losing Heroine Stares Back Into You):
AniDB Id - 284118
IMDb Id - tt32965561
TheTVDB Episode Id - 10535661



Blue Lock series:
AniDB Id - N/A
IMDb Id - tt15222080
TheMovieDb Series Id - 131041
TheTVDB Numerical Series Id - 408629

Blue lock Season 2:
TheTVDB Season Id - N/A

Blue lock s2e10 (The Subs Take to the Stage):
AniDB Id - N/A
IMDb Id - N/A
TheTVDB Episode Id - 10559634

**Comment by vosmiic** [comment]
You shouldn't really have to change any of the metadata settings, Jellyfin should handle it itself so you are fine to continue leaving it alone to do its thing. 
It is odd that the plugin isn't detecting the AniDB ID while it is working, and then is able to detect the AniDB after a seemingly random amount of time. It would suggest that something is changing the metadata but that wouldn't explain why it begins working again after restarting Jellyfin.
I guess one way to find out if something odd is happening to the metadata is to restart Jellyfin, capture the metadata and when you notice the plugin begin to fail for a specific show capture the metadata again and compare to see if anything has changed. Rather laborious I know but I'm a bit stumped as to what could be causing this issue.
